### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ivan-podgornov** [ivan-podgornov/colibri#1]
# MVP

## Main scenario

1. The user installs a CLI via NPM and correctly fills in the package.json file.
2. He can then run `cli dev` to develop React components locally and view them in a panel.
3. Once the components are ready, the user runs `cli build` to build the project and place the files in the dist folder.
4. Running `cli start` launches a development server that serves static files from the dist folder.
5. The user pushes his components to GitHub, triggering a workflow with a GitHub action to deploy the branch to GitHub Pages.
6. The user goes to the panel and specifies the address of github pages in the component settings, selecting the stage mode to view the components in the current branch.
7. After merging changes, the user specifies the production version of his components, turns off stage mode, and views the components in the main branch.
8. It's incredible!

## Roadmap

- [x] #2
- [ ] Editing, #8 and removing of remote components
- [ ] HOT reload for remote components (optional)
- [x] Deploy panel to vercel
- [x] #23
- [ ] Deploy example components to github pages
- [ ] Move module federation plugin to own package
- [ ] #18
- [ ] #26

**Comment by ivan-podgornov** [comment]
Move to millestone: https://github.com/ivan-podgornov/colibri/milestone/1
